# Generated by Django 2.0 on 2017-12-22 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TaskType'),
        ),
    ]
