# Generated by Django 2.0 on 2017-12-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171221_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskendtime',
            field=models.DateTimeField(null=True),
        ),
    ]
