# Generated by Django 2.0 on 2017-12-22 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_task_taskendtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskcurrentstage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stagename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='taskstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='taskcurrentstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.taskcurrentstage'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.taskstatus'),
        ),
    ]
