# Generated by Django 2.0 on 2017-12-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171221_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='executable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binarypath', models.CharField(max_length=256, null='Ture')),
                ('binaryhost', models.CharField(max_length=256, null='Ture')),
                ('healthcheckpath', models.CharField(max_length=256, null='Ture')),
            ],
        ),
        migrations.CreateModel(
            name='returncode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returncodetype', models.CharField(max_length=20)),
                ('returncodevalue', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='taskcurrentstage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.taskcurrentstage'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskstatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.taskstatus'),
        ),
        migrations.AddField(
            model_name='executable',
            name='codefailure',
            field=models.ForeignKey(null='Ture', on_delete=django.db.models.deletion.CASCADE, related_name='fail_code', to='dashboard.returncode'),
        ),
        migrations.AddField(
            model_name='executable',
            name='codesuccess',
            field=models.ForeignKey(null='Ture', on_delete=django.db.models.deletion.CASCADE, related_name='success_code', to='dashboard.returncode'),
        ),
        migrations.AddField(
            model_name='taskcurrentstage',
            name='stageprogram',
            field=models.ForeignKey(null='Ture', on_delete=django.db.models.deletion.CASCADE, to='dashboard.executable'),
        ),
    ]
