# Generated by Django 2.0 on 2017-12-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20171224_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='statusbehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusbehavior', models.CharField(default='to-be-execute', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='statusbehavior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.statusbehavior'),
        ),
    ]
