# Generated by Django 2.0 on 2018-01-06 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_taskaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskaction',
            name='Taskid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dashboard.Task'),
        ),
    ]
